/**
 * Adapter for opencode. OpenCode has no JSON hooks config; it auto-loads local
 * plugins from ~/.config/opencode/plugins/. We generate a small plugin that
 * listens for session.idle and shells out to notify.js.
 */
import fs from 'node:fs';
import path from 'node:path';

export const PLUGIN_DIR = path.join('.config', 'opencode', 'plugins');
export const PLUGIN_FILE = 'agent-notify.js';

export function pluginPath(home) {
  return path.join(home, PLUGIN_DIR, PLUGIN_FILE);
}

export function detect(home) {
  // opencode is installed iff the binary exists or its global config dir exists.
  return fs.existsSync(path.join(home, PLUGIN_DIR)) ? ['opencode'] : [];
}

export function pluginSource(notifyPath) {
  // NOTE: interpolating notifyPath into the source. It is a repo-absolute path
  // built from __dirname, not user input, so no injection surface here.
  return `// Generated by agent-notify — do not edit manually.
export const AgentNotify = async ({ $ }) => {
  return {
    event: async ({ event }) => {
      if (event.type !== "session.idle") return;
      const sid = event.properties?.sessionID || "?";
      try {
        await $\`node ${notifyPath} --agent opencode --session \${sid}\`.quiet();
      } catch { /* never crash opencode */ }
    },
  };
};
`;
}

export function enable(home, notifyPath) {
  const file = pluginPath(home);
  const dir = path.dirname(file);
  if (!fs.existsSync(dir)) {
    return { agent: 'opencode', changed: false, detail: 'plugin dir not found, skipped' };
  }
  const existing = fs.existsSync(file) ? fs.readFileSync(file, 'utf8') : '';
  if (existing.includes(notifyPath)) return { agent: 'opencode', changed: false, detail: 'already installed' };
  fs.mkdirSync(dir, { recursive: true });
  fs.writeFileSync(file, pluginSource(notifyPath));
  return { agent: 'opencode', changed: true, detail: `plugin → ${file}` };
}

export function disable(home, notifyPath) {
  const file = pluginPath(home);
  if (!fs.existsSync(file)) return { agent: 'opencode', changed: false, detail: 'no plugin file' };
  const existing = fs.readFileSync(file, 'utf8');
  if (!existing.includes(notifyPath)) return { agent: 'opencode', changed: false, detail: 'not installed' };
  fs.unlinkSync(file);
  return { agent: 'opencode', changed: true, detail: 'plugin removed' };
}
